create table if not exists public.slack_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  slack_id text not null,
  channel_name text,
  author_name text,
  content text,
  timestamp timestamptz,
  fetched_at timestamptz not null default now(),
  unique(user_id, slack_id)
);

create index if not exists slack_items_user_timestamp_idx
  on public.slack_items (user_id, timestamp desc);

create table if not exists public.github_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  github_id text not null,
  type text,
  title text,
  repo text,
  url text,
  state text,
  timestamp timestamptz,
  fetched_at timestamptz not null default now(),
  unique(user_id, github_id)
);

create index if not exists github_items_user_timestamp_idx
  on public.github_items (user_id, timestamp desc);

alter table public.slack_items enable row level security;
alter table public.github_items enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'slack_items'
      and policyname = 'own slack'
  ) then
    create policy "own slack" on public.slack_items
      for all to authenticated
      using ((select auth.uid()) = user_id)
      with check ((select auth.uid()) = user_id);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'github_items'
      and policyname = 'own github'
  ) then
    create policy "own github" on public.github_items
      for all to authenticated
      using ((select auth.uid()) = user_id)
      with check ((select auth.uid()) = user_id);
  end if;
end
$$;

grant select, insert, update, delete on public.slack_items to authenticated;
grant select, insert, update, delete on public.github_items to authenticated;
grant usage, select on all sequences in schema public to authenticated;
