alter table public.user_integrations
  add column if not exists expires_at timestamptz,
  add column if not exists canvas_domain text;

create table if not exists public.canvas_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users (id) on delete cascade,
  canvas_id text not null,
  type text not null default 'assignment',
  title text not null,
  course_name text,
  due_date timestamptz,
  points numeric,
  description text,
  status text not null default 'todo',
  fetched_at timestamptz not null default timezone('utc'::text, now()),
  unique (user_id, canvas_id)
);

create index if not exists canvas_items_user_due_idx
  on public.canvas_items (user_id, due_date);

create table if not exists public.gmail_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users (id) on delete cascade,
  gmail_id text not null,
  thread_id text not null,
  from_name text,
  from_email text,
  subject text,
  preview text,
  body text,
  timestamp timestamptz,
  is_read boolean not null default false,
  labels text[] not null default '{}',
  unique (user_id, gmail_id)
);

create index if not exists gmail_items_user_timestamp_idx
  on public.gmail_items (user_id, timestamp desc);

create table if not exists public.user_style_profiles (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users (id) on delete cascade unique,
  tone text,
  avg_length integer,
  formality_score numeric,
  style_description text,
  sample_phrases text[] not null default '{}',
  updated_at timestamptz not null default timezone('utc'::text, now())
);

create table if not exists public.discord_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users (id) on delete cascade,
  discord_id text not null,
  guild_id text,
  guild_name text,
  channel_id text not null,
  channel_name text,
  author_name text,
  content text,
  timestamp timestamptz,
  fetched_at timestamptz not null default timezone('utc'::text, now()),
  unique (user_id, discord_id)
);

create index if not exists discord_items_user_timestamp_idx
  on public.discord_items (user_id, timestamp desc);

alter table public.canvas_items enable row level security;
alter table public.gmail_items enable row level security;
alter table public.user_style_profiles enable row level security;
alter table public.discord_items enable row level security;

grant select, insert, update, delete on public.users to authenticated;
grant insert on public.waitlist to anon, authenticated;
grant select, insert, update, delete on public.user_integrations to authenticated;
grant select, insert, update, delete on public.canvas_items to authenticated;
grant select, insert, update, delete on public.gmail_items to authenticated;
grant select, insert, update, delete on public.user_style_profiles to authenticated;
grant select, insert, update, delete on public.discord_items to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant usage, select on sequence public.waitlist_id_seq to anon;
revoke all on function public.handle_new_user() from public, anon, authenticated;

create policy "Users manage their own canvas items"
  on public.canvas_items for all to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy "Users manage their own gmail items"
  on public.gmail_items for all to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy "Users manage their own style profile"
  on public.user_style_profiles for all to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy "Users manage their own discord items"
  on public.discord_items for all to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);
