create table if not exists public.user_integrations (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users (id) on delete cascade,
  integration_name text not null,
  access_token text,
  refresh_token text,
  connected_at timestamptz not null default timezone('utc'::text, now()),
  unique (user_id, integration_name)
);

create index if not exists user_integrations_user_id_idx
  on public.user_integrations (user_id);

alter table public.user_integrations enable row level security;

create policy "Users can read their own integrations"
  on public.user_integrations
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

create policy "Users can insert their own integrations"
  on public.user_integrations
  for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

create policy "Users can update their own integrations"
  on public.user_integrations
  for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy "Users can delete their own integrations"
  on public.user_integrations
  for delete
  to authenticated
  using ((select auth.uid()) = user_id);
