create table if not exists public.waitlist (
  id bigint generated by default as identity primary key,
  email text not null,
  created_at timestamptz not null default timezone('utc'::text, now())
);

create unique index if not exists waitlist_email_unique
  on public.waitlist (lower(email));

alter table public.waitlist enable row level security;

create policy "Anyone can join the waitlist"
  on public.waitlist
  for insert
  to anon, authenticated
  with check (true);
