create table if not exists public.custom_connectors (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  name text not null,
  url text not null,
  api_key text,
  feed_type text not null default 'json',
  created_at timestamptz not null default now()
);

create index if not exists custom_connectors_user_idx
  on public.custom_connectors (user_id);

create table if not exists public.custom_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  source_name text not null,
  item_id text not null,
  title text,
  body text,
  url text,
  timestamp timestamptz,
  fetched_at timestamptz not null default now(),
  unique(user_id, source_name, item_id)
);

create index if not exists custom_items_user_timestamp_idx
  on public.custom_items (user_id, timestamp desc);

alter table public.custom_connectors enable row level security;
alter table public.custom_items enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'custom_connectors'
      and policyname = 'own connectors'
  ) then
    create policy "own connectors" on public.custom_connectors
      for all to authenticated
      using ((select auth.uid()) = user_id)
      with check ((select auth.uid()) = user_id);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'custom_items'
      and policyname = 'own custom items'
  ) then
    create policy "own custom items" on public.custom_items
      for all to authenticated
      using ((select auth.uid()) = user_id)
      with check ((select auth.uid()) = user_id);
  end if;
end
$$;

grant select, insert, update, delete on public.custom_connectors to authenticated;
grant select, insert, update, delete on public.custom_items to authenticated;
grant usage, select on all sequences in schema public to authenticated;
